CREATE DATABASE mensajeria;
USE mensajeria;

CREATE TABLE USUARIOS(
	ID_USUARIO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    TELEFONO VARCHAR(10) NOT NULL UNIQUE,
    CONTRASENA VARCHAR(16) NOT NULL,
    SEXO VARCHAR(50) NOT NULL,
    FECHA_NACIMIENTO DATE NOT NULL,
    IMAGEN_PERFIL LONGBLOB
);

CREATE TABLE DIRECCIONES(
	ID_DIRECCION INT NOT NULL PRIMARY KEY AUTO_INCREMENT, 
    CALLE VARCHAR(255) NOT NULL,
    NUMERO VARCHAR(50) NOT NULL,
    CODIGO_POSTAL VARCHAR(10) NOT NULL,
    ID_USUARIO INT NOT NULL,
	FOREIGN KEY(ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO)
);

CREATE TABLE CHATS(
	ID_CHAT INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOMBRE_USUARIO VARCHAR(255) NOT NULL
);

CREATE TABLE PARTICIPANTES(
	ID_PARTICIPANTE INT NOT NULL PRIMARY KEY AUTO_INCREMENT, 
    ID_USUARIO INT NOT NULL,
    ID_CHAT INT NOT NULL,
    FOREIGN KEY(ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO),
    FOREIGN KEY(ID_CHAT) REFERENCES CHATS(ID_CHAT)
);

CREATE TABLE MENSAJES(
	ID_MENSAJE INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    TEXTO VARCHAR(500),
    FECHA_HORA_REGISTRO DATETIME,
    IMAGEN_MENSAJE LONGBLOB,
    ID_USUARIO INT NOT NULL,
    ID_CHAT INT NOT NULL,
    FOREIGN KEY(ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO),	
    FOREIGN KEY(ID_CHAT) REFERENCES CHATS(ID_CHAT)
);

INSERT INTO USUARIOS(TELEFONO, CONTRASENA, SEXO, FECHA_NACIMIENTO, IMAGEN_PERFIL)
VALUES ('5551234567', 'password123', 'M', '1990-05-15', 'perfil1.jpg'),
('5557654321', 'securepass456', 'F', '1985-10-20', 'perfil2.jpg'),
('5559876543', 'mypassword789', 'O', '2000-01-01', 'perfil3.jpg');

INSERT INTO DIRECCIONES(CALLE, NUMERO, CODIGO_POSTAL, ID_USUARIO) 
VALUES ('Av. Reforma', 1234, 11000, 1),
('Calle Gran Vía', 567, 28013, 2),
('Boulevard Saint-Germain', 750, 75006, 3);

INSERT INTO CHATS(NOMBRE_USUARIO)
VALUES ('juan_perez'),
('maria_gomez'),
('carlos_lopez');

INSERT INTO MENSAJES(TEXTO, FECHA_HORA_REGISTRO, IMAGEN_MENSAJE, ID_USUARIO, ID_CHAT)
VALUES ('Hola, ¿cómo estás?', '2024-05-24 10:15:30', 'imagen1.jpg', 1, 1),
('Nos vemos a las 6.', '2024-05-24 12:45:00', 'imagen2.png', 2, 2),
('¡Feliz cumpleaños!', '2024-05-24 09:00:00', 'imagen3.gif', 3, 3);

INSERT INTO PARTICIPANTES(ID_USUARIO, ID_CHAT)
VALUES (1, 1),
(2, 2),
(3, 3);

SELECT * FROM DIRECCIONES;
SELECT * FROM USUARIOS; 
SELECT * FROM CHATS;
SELECT * FROM MENSAJES;
SELECT * FROM PARTICIPANTES;
--